name: Call list create issue


#Myissue2
on:
    pull_request:
      types: 
        - closed
        - opened

    push:
      branches:
        - main
      

jobs:
    # unit tests
    units:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - run: npm ci
        #- run: npm test
  
    # test action works running from the graph
    test:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: ./
          id: issue
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Test Issue
            body: Test issue body
            assignees: smiti6812
        - run: echo "${{ steps.issue.outputs.issue }}"
        - name: Show PR number
          run: echo  "${{ github.event.pull_request.number }}"    




   
      
