name: Call list create issue

on:
    pull_request:
      types:
       - opened
       - closed
    push:
      branches:
        - main
        - "releases/*"
jobs:
    # unit tests
    units:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - run: npm ci  
  
    # test action works running from the graph
    test:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - uses: ./
          id: issue
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            title: Test Issue
            body: Test issue body
            assignees: alialaa
        - run: echo ${{ steps.issue.outputs.issue }}         



   
      
